include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    library_private_types_in_public_api: ignore
    file_names: ignore
    avoid_print: ignore
    avoid_function_literals_in_foreach_calls: ignore
    sort_child_properties_last: ignore
    avoid_returning_null_for_void: ignore
    use_super_parameters: ignore
    use_key_in_widget_constructors: ignore
