name: exampleapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  flutter_svg: ^2.0.17
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
